version: '3.1'

services:

  mongo:
    container_name: medusa-mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    command: [ --auth ]
    ports:
      - 27017:27017
    volumes:
      - "mongodata:/data/db"
    networks:
      - network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
    networks:
      - network

volumes:
  mongodata:

networks:
  network:
